@baseUrl = http://localhost:8080

#@name create wallet
POST {{baseUrl}}/wallets
Content-Type: application/json

{
  "fullName": "Romulo Sobreira",
  "cpfCnpj": "asasas",
  "email": "romulo@email.com.br",
  "password": "123456",
  "walletTypeId": "USER"
}


########
#@name tranfer
POST {{baseUrl}}/transfer
Content-Type: application/json

{
  "value": 20,
  "payer": 5,
  "payee": 4
}